/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphane;


import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Bilgehan
 */
public class KutuphaneIslemleri extends javax.swing.JDialog {
    DefaultTableModel model ;
    Islem islem = new Islem();
    
    /**
     * Creates new form KutuphaneIslemleri
     */
    public KutuphaneIslemleri(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model =(DefaultTableModel) tablo.getModel();
        kitap_goruntule();
    }


    public void kitap_goruntule(){
        model.setRowCount(0);
        
        ArrayList<KitapProperties> kitapOzellik = new ArrayList<KitapProperties>();
        kitapOzellik = islem.kitaplari_getir();
        
        if(kitapOzellik != null){
            for (KitapProperties kp: kitapOzellik ){
                Object [] eklenecek = {kp.getKitapAd(),kp.getKitapYazari(),kp.getKitapBaskiYil(),kp.getKitapSayfaSayisi(),kp.getKitapDil(),kp.getKitapYayinEvi(),kp.getKitapNo()};
                
                model.addRow(eklenecek);
            }
            
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kitapsayfa_alan = new javax.swing.JTextField();
        kitapadi_alan = new javax.swing.JTextField();
        kitapdil_alan = new javax.swing.JTextField();
        kitapyazar_alan = new javax.swing.JTextField();
        kitapyayin_alan = new javax.swing.JTextField();
        kitapbaski_alan = new javax.swing.JTextField();
        kitapekle_buton = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        kitapSil = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        anasayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Kitap Yazarı", "Baskı Yılı", "Sayfa Sayısı", "Kitap Dili", "Yayın Evi", "Kitap No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        jLabel2.setText("Kitap Adı : ");

        jLabel3.setText("Kitap Yazarı :");

        jLabel4.setText("Sayfa Sayısı :");

        jLabel5.setText("Kitap Dili :");

        jLabel6.setText("Yayın Evi :");

        jLabel7.setText("Baskı Yılı :");

        kitapekle_buton.setText("Kitap Ekle");
        kitapekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapekle_butonActionPerformed(evt);
            }
        });

        guncelle.setText("Kitap Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        kitapSil.setText("Kitap Sil");
        kitapSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapSilActionPerformed(evt);
            }
        });

        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 0));

        anasayfa.setText("Anasayfa");
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kitapekle_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(kitapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(51, 51, 51)
                                        .addComponent(kitapadi_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kitapbaski_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kitapyazar_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kitapsayfa_alan, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(kitapdil_alan)
                                    .addComponent(kitapyayin_alan))))
                        .addContainerGap(156, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anasayfa)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kitapsayfa_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitapadi_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kitapdil_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(kitapyazar_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kitapyayin_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitapbaski_alan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(60, 60, 60)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapekle_buton)
                    .addComponent(guncelle)
                    .addComponent(kitapSil))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitapekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapekle_butonActionPerformed
        mesaj_yazisi.setText("");
        
        
        String ad=kitapadi_alan.getText();
        String yazar=kitapyazar_alan.getText();
        String baski=kitapbaski_alan.getText();
        String sayfa=kitapsayfa_alan.getText();
        String dil=kitapdil_alan.getText();
        String yayınevi=kitapyayin_alan.getText();
        
        islem.kitapEkle(ad,yazar,baski,sayfa,dil,yayınevi);
        
        kitap_goruntule();
        
        mesaj_yazisi.setText("Yeni kitap başarıyla eklendi..");
        
    }//GEN-LAST:event_kitapekle_butonActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
        int selectRow = tablo.getSelectedRow();
        
        kitapadi_alan.setText(model.getValueAt(selectRow,0).toString());
        kitapyazar_alan.setText(model.getValueAt(selectRow,1).toString());
        kitapbaski_alan.setText(model.getValueAt(selectRow,2).toString());
        kitapsayfa_alan.setText(model.getValueAt(selectRow,3).toString());
        kitapdil_alan.setText(model.getValueAt(selectRow,4).toString());
        kitapyayin_alan.setText(model.getValueAt(selectRow,5).toString());
       
        
        
    }//GEN-LAST:event_tabloMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        
        
        String ad=kitapadi_alan.getText();
        String yazar=kitapyazar_alan.getText();
        String baski=kitapbaski_alan.getText();
        String sayfa=kitapsayfa_alan.getText();
        String dil=kitapdil_alan.getText();
        String yayınevi=kitapyayin_alan.getText();
        
        int selectedRow = tablo.getSelectedRow();
         if (selectedRow == -1) {
            
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışanlar Tablosu şu anda boş. ");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir çalışan seçin.");
            }
        }
        else {
            int no = (int)model.getValueAt(selectedRow,6);
            islem.kitapGuncelle(ad,yazar,baski,sayfa,dil,yayınevi,no);
            kitap_goruntule();
            mesaj_yazisi.setText("Çalışan başarıyla güncellendi...");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void kitapSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapSilActionPerformed
       mesaj_yazisi.setText("");
        
       int selectedrow =tablo.getSelectedRow();
       
       if (selectedrow == -1) {
           if (model.getRowCount() == 0 ) {
               mesaj_yazisi.setText("Çalışan tablosu şu anda boş...");
           }
           else {
               mesaj_yazisi.setText("Lütfen silinecek bir çalışan seçin...");
           }
      
       }
       else {
           int no = (int)model.getValueAt(selectedrow,6);
           
           islem.kitapSil(no);
           
           kitap_goruntule();
           
           mesaj_yazisi.setText("Çalışan başarıyla silindi...");
           
           
           
           
       }
        
    }//GEN-LAST:event_kitapSilActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
       
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KutuphaneIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KutuphaneIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KutuphaneIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KutuphaneIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KutuphaneIslemleri dialog = new KutuphaneIslemleri(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kitapSil;
    private javax.swing.JTextField kitapadi_alan;
    private javax.swing.JTextField kitapbaski_alan;
    private javax.swing.JTextField kitapdil_alan;
    private javax.swing.JButton kitapekle_buton;
    private javax.swing.JTextField kitapsayfa_alan;
    private javax.swing.JTextField kitapyayin_alan;
    private javax.swing.JTextField kitapyazar_alan;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
